### ISSUE TITLE
Not working on Paper #134 1.15.2

### ISSUE THREAD

**Issue by Cavallium** [Olexorus/WitherAC#39]
WitherAC crashes in Paper 134.

It was working with Paper 132.

Probably it's related with the patch #3027

`[13:42:26 INFO]: [WitherAC] Enabling WitherAC v0.18.1
[13:42:26 ERROR]: Error occurred while enabling WitherAC v0.18.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.gmail.olexorus.witherac.li.<init>(al:53) ~[?:?]
        at com.gmail.olexorus.witherac.Ih.<init>(bh:156) ~[?:?]
        at com.gmail.olexorus.witherac.WitherAC.onEnable(mg:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-134]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-134]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-134]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-134]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-134]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-134]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-134]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-134]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.IllegalStateException: Unable to find method null ([class net.minecraft.server.v1_15_R1.ServerConnection]).
        at com.gmail.olexorus.witherac.Jh.I(sb:17) ~[?:?]
        at com.gmail.olexorus.witherac.Jh.I(sb:244) ~[?:?]
        at com.gmail.olexorus.witherac.Jh.I(sb:92) ~[?:?]
        at com.gmail.olexorus.witherac.RH.<clinit>(jk:213) ~[?:?]
        ... 12 more
[13:42:26 INFO]: [WitherAC] Disabling WitherAC v0.18.1`

**Comment by Olexorus** [comment]
Sorry, totally forgot to respond to this issue here on Github, this should be fixed in 0.18.3
