### ISSUE TITLE
Could not Find Data Player InHerePlayerName

### ISSUE THREAD

**Issue by aril3721** [Olexorus/WitherAC#58]
[05:29:37 ERROR]: [WitherAC] Unhandled exception occured in onPacketReceiving(PacketEvent) for WitherAC
java.lang.NullPointerException: Could not find data for player Tochka228
        at com.gmail.olexorus.witherac.eI.m(sl:37) ~[?:?]
        at com.gmail.olexorus.witherac.XG.g(fe:92) ~[?:?]
        at com.gmail.olexorus.witherac.xg.onPacketReceiving(zd:141) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:348) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[05:29:37 ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayInKeepAlive@6ed59f4a[
    a=1643050827
    
    i Dont Know Why Every I Restarted My Server This Message Spamming On My Console

**Comment by aril3721** [comment]
And This More Message When Another Player Join

[05:30:13 ERROR]: Could not pass event PlayerTeleportEvent to WitherAC v0.23.1
[05:30:13 ERROR]: Suspected Plugins: 
[05:30:13 ERROR]:       WitherAC{enabled,ver=0.23.1,path=plugins/WitherAC_0.23.1.jar}
[05:30:13 ERROR]: Exception details below: 
java.lang.NullPointerException: Could not find data for player GGerryz
        at com.gmail.olexorus.witherac.eI.m(sl:37) ~[?:?]
        at com.gmail.olexorus.witherac.lh.m(zd:231) ~[?:?]
        at com.gmail.olexorus.witherac.lh.m(zd:215) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor87.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1437) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1416) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1406) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.EntityPlayer.enderTeleportTo(EntityPlayer.java:1847) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.EntityLiving.a(EntityLiving.java:2211) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.EntityLiving.stopRiding(EntityLiving.java:3033) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.EntityHuman.stopRiding(EntityHuman.java:975) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.EntityPlayer.stopRiding(EntityPlayer.java:1458) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.EntityPlayer.stopRiding(EntityPlayer.java:1453) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:549) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1782) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:332) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:184) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:555) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1476) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:398) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1295) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1016) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-24]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by aril3721** [comment]
And Every I Chat It Make A Lagging Or Delays 1 - 3 seconds
